### ISSUE TITLE
Could we add a branch to your repo ?

### ISSUE THREAD

**Issue by Dante-Berth** [hbonnavaud/RLFramework#2]
Hello nice repo is it possible to create a branch ? I need it for my personal project.

**Comment by hbonnavaud** [comment]
Hi,
 - If you want to create you own RL experiments, download or fork the repository, so you can do your stuff on your side.
 - If you want to add elements to the project, create a fork, add your elements in it, and send a pull-request.

**Comment by Dante-Berth** [comment]
Okay thanks you
